### ISSUE TITLE
article.Rmd not (yet) outputting CiTO in RStudio

### ISSUE THREAD

**Issue by schymane** [tarleb/jcheminf-test#2]
@tarleb @egonw I'm documenting the issue with some screenshots, working directly from `article.Rmd` in RStudio from my own repo created using the template option: https://github.com/schymane/markdown-jcheminf-research

This works (i.e. not using any fancy options),
```
output:
  pdf_document:
bibliography: bibliography.bib
``` 
but two refs are (obviously) unrecognised because of the CiTO tags: 
![image](https://user-images.githubusercontent.com/4070141/111899006-ea0dd780-8a29-11eb-863e-935070b5b872.png)
Output: 
![image](https://user-images.githubusercontent.com/4070141/111899013-f7c35d00-8a29-11eb-8a11-bdb09c6c6c64.png)

I had issues last night with two outputs in one specification, so just concentrating on the PDF for now (I also got doc working last night), it does *not* like `-- citeproc`  ...

![image](https://user-images.githubusercontent.com/4070141/111899050-4e309b80-8a2a-11eb-9217-2663963a0d60.png)

...and if you look at the previous RStudio image it seems to receive it as a filter instead

So this "works": 

```
output:
  pdf_document:
   pandoc_args:
   - --lua-filter=filters/extract-cito.lua
   - --filter=C:/Program Files/RStudio/bin/pandoc/pandoc-citeproc.exe
   - --lua-filter=filters/insert-cito-in-ref.lua
cito-bibliography: bibliography.bib
```

![image](https://user-images.githubusercontent.com/4070141/111899109-b7181380-8a2a-11eb-8e91-0f651ef5e21a.png)
but ... no CiTO in the output ... 

![image](https://user-images.githubusercontent.com/4070141/111899118-c8612000-8a2a-11eb-87ec-48e3bc579f51.png)

Any ideas? Thanks so much for your efforts!
